#!/bin/sh -e


PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

# Load default env variables from profiles(e.g. /etc/profile.d/weston.sh)
. /etc/profile

start_ui()
{
	/usr/miyoo/bin/runmiyoo.sh &
}

stop_ui()
{
	killall MainUI
	killall runmiyoo.sh
}

case "$1" in
	start)
		echo "start ui begin " `cat /proc/uptime`
		start_ui
		echo "start ui end " `cat /proc/uptime`
		;;
	stop)
		echo -n "stoping ui... "
		stop_ui || true
		echo "done."
		;;
	restart|reload)
		echo -n "stoping ui... "
		start_ui && sleep .3
		echo "done."

		echo -n "starting ui... "
		start_ui
		echo "done."
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
